### ISSUE TITLE
TwitterKitResources.bundle error

### ISSUE THREAD

**Issue by GorkaMM** [zergtmn/Fabric#2]
Hi,

I'm getting this error when compiling:
```
rsync: link_stat "/xxxxx/Pods/${BUILT_PRODUCTS_DIR}/TwitterKitResources.bundle" failed: No such file or directory (2)
...
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

I followed the steps in your `README`, installing first the frameworks through Fabric's Mac app and then removing them and installing the pods, but this happened again. I tried forking this repo and changing the `resource_bundle` from the Podspec to `resource`, but it kept breaking. I don't know what else to try.

Edit: I'm using Cocoapods 0.36.0.beta.2 and Xcode 6.1.1

**Comment by zergtmn** [comment]
Did you `#import <TwitterKit/TwitterKit.h>`?
I also have build errors if I use 'Fabric/Twitter' subspec but don't import the framework. Dunno how to fix it yet.

**Comment by GorkaMM** [comment]
Yes, I'm importing it:
```
#import <Fabric/Fabric.h>
#import <TwitterKit/TwitterKit.h>
```

I think the problem is in how CocoaPods handles `resource_bundle`. The problem may be there, I'm not sure. I've been checking other pods with resources bundles and none of them has this `${BUILT_PRODUCTS_DIR}` in the `Pods-resources.sh` file, where the error is coming from.

**Comment by danieljacobarcher** [comment]
@GorkaMM I'm also getting this issue. Did you find the problem?

**Comment by GorkaMM** [comment]
@danieljacobarcher I ended up using Fabric's Mac app to keep everything updated and more easily manageable. At the end, this app they provide is taking care of managing those dependencies, so I moved to it for their frameworks.

**Comment by AliSoftware** [comment]
Probably fixed by #13 ?

**Comment by rockrep** [comment]
I'm still getting this same error with 1.2.3.   
TwitterKit.framework/TwitterKit symlinks to Versions/Current/TwitterKit.    Should Versions/A be changed to Versions/Current in the podspec to fix this?

**Comment by AliSoftware** [comment]
No: `Versions/Current` is itself a symlink so that wouldn't work. `Versions/A` (or whatever specific version as long as the path doesn't contains a symlink) is the good way to go.

**Comment by govindshah** [comment]
I dragged and dropped TwitterKitResources.bundle file in Resources folder in xcode and worked for me.
